
export const GET_PHARMACIES_REQUEST = 'GET_PHARMACIES_REQUEST';
export const GET_PHARMACIES_SUCCESS = 'GET_PHARMACIES_SUCCESS';
export const GET_PHARMACIES_FAILED = 'GET_PHARMACIES_FAILED';

export const UPDATE_PHARMACIE_REQUEST = 'UPDATE_PHARMACIE_REQUEST';
export const UPDATE_PHARMACIE_SUCCESS = 'UPDATE_PHARMACIE_SUCCESS';
export const UPDATE_PHARMACIE_FAILED = 'UPDATE_PHARMACIE_FAILED';

export const ADD_PHARMACIE_REQUEST = 'ADD_PHARMACIE_REQUEST';
export const ADD_PHARMACIE_SUCCESS = 'ADD_PHARMACIE_SUCCESS';
export const ADD_PHARMACIE_FAILED = 'ADD_PHARMACIE_FAILED';

export const DELETE_PHARMACIE_REQUEST = 'DELETE_PHARMACIE_REQUEST';
export const DELETE_PHARMACIE_SUCCESS = 'DELETE_PHARMACIE_SUCCESS';
export const DELETE_PHARMACIE_FAILED = 'DELETE_PHARMACIE_FAILED';