
export const GET_MEDICAMENTS_REQUEST = 'GET_MEDICAMENTS_REQUEST';
export const GET_MEDICAMENTS_SUCCESS = 'GET_MEDICAMENTS_SUCCESS';
export const GET_MEDICAMENTS_FAILED = 'GET_MEDICAMENTS_FAILED';

export const UPDATE_MEDICAMENT_REQUEST = 'UPDATE_MEDICAMENT_REQUEST';
export const UPDATE_MEDICAMENT_SUCCESS = 'UPDATE_MEDICAMENT_SUCCESS';
export const UPDATE_MEDICAMENT_FAILED = 'UPDATE_MEDICAMENT_FAILED';

export const ADD_MEDICAMENT_REQUEST = 'ADD_MEDICAMENT_REQUEST';
export const ADD_MEDICAMENT_SUCCESS = 'ADD_MEDICAMENT_SUCCESS';
export const ADD_MEDICAMENT_FAILED = 'ADD_MEDICAMENT_FAILED';

export const DELETE_MEDICAMENT_REQUEST = 'DELETE_MEDICAMENT_REQUEST';
export const DELETE_MEDICAMENT_SUCCESS = 'DELETE_MEDICAMENT_SUCCESS';
export const DELETE_MEDICAMENT_FAILED = 'DELETE_MEDICAMENT_FAILED';